name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-zark-oidc-platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/zarkhq/oidc-platform:latest
          docker run ghcr.io/zarkhq/oidc-platform:latest
          docker push ghcr.io/zarkhq/oidc-platform:latest